# Enhanced configuration for aircraft image classification

# Paths configuration
paths:
  dataset: "dataset"
  output: "results/filtered_dataset"
  results: "results/metrics"

# CLIP model configuration
model:
  name: "openai/clip-vit-base-patch16"  # Consider trying larger models for better performance
  # openai/clip-vit-base-patch16
  # openai/clip-vit-base-patch32
  # openai/clip-vit-large-patch14
  # openai/clip-vit-large-patch14-336
  # laion/CLIP-ViT-L-14-laion2B-s32B-b82K
  # openai/clip-RN101
  # "model/ViT-B32_fine_tuning.pt"
  device: null  # Auto-select (cuda if available, else cpu)

# Category definitions with expanded prompts and refined thresholds
categories:
  - name: art_images
    positive_texts:
      - "a poster of military aircraft"
      - "drawing of military aircraft"
      - "painting of military aircraft"
      - "journal military aircraft"
      - "an illustration of an airplane"
      - "a digital art of fighter jet"
      - "a painting of an aircraft"
      - "a photograph printed in a book with text"
      - "an airplane image with typography overlay"
      - "magazine cover with a jet fighter"
      - "infographic showing parts of a military aircraft"
      - "aviation art print of a warplane"
      - "aircraft profile illustration with labels"
      - "vintage military aircraft poster"
      - "vector art of a fighter jet"
      - "technical drawing of a jet engine"
      - "exploded diagram of aircraft components"
      - "comic book panel featuring a jet"
      - "military plane sketch in pencil"
      - "retro poster of supersonic fighter"
      - "stylized jet on promotional aviation poster"
      - "advertising leaflet with military airplane"
      - "3D render of fighter aircraft in poster format"
      - "CGI image of jet with overlaid text"
    negative_texts:
      - "a photograph of an military aircraft"
      - "a photograph of an airplane"
      - "aircraft in flight"
      - "photograph of a military jet on the runway"
      - "military aircraft captured during takeoff"
      - "daylight photo of jet parked on concrete"
    threshold: 0.7
    min_difference: 0  # Minimum difference from next highest category

  - name: satellite_images
    positive_texts:
      - "satellite image of military airbase"
      - "overhead view of military base from space"
      - "satellite image of military airport"
      - "military base seen from space"
      - "satellite image of airbase"
      - "satellite images of airport"
      - "images of airport from above"
      - "drone image of fighter jet from above"
      - "top-down view of military jet on runway"
      - "overhead drone shot of parked warplane"
      - "aerial view of fighter aircraft on tarmac"
      - "top-down UAV image of military aircraft"
      - "clear drone photo of jet on airbase"
      - "surveillance drone image of fighter jet"
      - "satellite image of fighter jet on runway"
      - "overhead satellite photo of military jet"
      - "space image of airbase with aircraft visible"
      - "high-resolution satellite photo of fighter aircraft"
      - "military planes visible on airbase from satellite"
      - "military aircraft on parking ramp seen from above"
      - "aircraft lineup on military airfield from drone"
      - "jets stationed at airbase seen from satellite"
      - "airplane hangars and jets seen from space"
      - "aerial view of hardened aircraft shelters"

    negative_texts:
      - "side image of military aircraft"
      - "bottom view of military aircraft"
      - "a photo of military aircraft on a runway"
    threshold: 0.55
    min_difference: 0  # Minimum difference from next highest category

  - name: top_view_aircraft
    positive_texts:
      - "military jet viewed from above"
      - "drone photo of aircraft from above"
      - "top view of a parked fighter jet"
      - "aerial top-down image of a military plane"
      - "looking down at military aircraft"
      - "photo from military jet cabin"
      - "a bird’s-eye photograph of a jet"
      - "view from cockpit of airplane cockpit"
      - "pilot’s eye view of plane interior"
      - "photo from inside aircraft cockpit"
      - "pilot view from cockpit"
      - "airplane interior view"
      - "view through windshield of a military jet"
      - "first-person perspective from airplane cabin"
      - "air-to-air photo of a fighter jet"
      - "jet photographed from another aircraft"
      - "close-up of military aircraft mid-flight from above"
      - "photo of airplane during midair refueling"
      - "two jets flying in formation, photographed from air"
      - "jet flying past photographed from cockpit of another plane"
      - "aerial refueling of a jet in midair"
      - "fighter jet connected to a tanker aircraft"
      - "plane refueling operation from above"
    negative_texts:
      - "side view of military aircraft"
      - "bottom view of military aircraft"
    threshold: 0.7
    min_difference: 0  # Minimum difference from next highest category

# Classification settings
classification:
  default_category: "normal_images"
  copy_to_folders: true
  save_results: true
  use_negative_prompts: false  # Enable negative prompt functionality
  confidence_strategy: "fixed"  # Options: "fixed", "adaptive"


# Evaluation configuration for comparing with manual classification
evaluation:
  manual_classification_dir: "sorted_dataset"  # Path to your manual classification directory
  low_quality_category: "shit_data"  # Category for low-quality images
  ignore_in_metrics: ["shit_data"]  # Categories to ignore when computing metrics (empty list means include all)
  # If you decide to exclude shit_data from metrics calculations:
  # ignore_in_metrics: ["shit_data"]